# stolen from https://github.com/hvr/multi-ghc-travis

env:
 - CABALVER=1.16 GHCVER=7.6.1
 - CABALVER=1.16 GHCVER=7.6.2
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.1
 - CABALVER=1.18 GHCVER=7.8.2
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head
  - env: CABALVER=1.22 GHCVER=7.10.2

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
# - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure --enable-tests -O0 --disable-library-profiling -v2
 - cabal build
 - cabal configure --enable-tests --enable-benchmarks -O0 --disable-library-profiling -v2
# - cabal install hspec
 - cabal test
 - cabal check
 - cabal sdist
 - cabal install --force-reinstalls dist/*-*.tar.gz
