sudo: required

env:
 - CABALVER=1.16 GHCVER=7.6.1
 - CABALVER=1.16 GHCVER=7.6.2
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.1
 - CABALVER=1.18 GHCVER=7.8.2
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head
 - STACK=STACK

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head

install:
 - sudo apt-get update
 - if [ -n "$STACK" ]; then sudo apt-get install libgmp-dev; fi
 - |
    if [ -z "$STACK" ]; then
      sudo add-apt-repository -y ppa:hvr/ghc
      sudo apt-get update
      time sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
      export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

      echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
      cabal update

    else
      wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
      echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main'|sudo tee /etc/apt/sources.list.d/fpco.list
      sudo apt-get update
      sudo apt-get install stack -y
    fi

script:
 - |
    if [ -n "$STACK" ]; then 
      (sudo stack setup; sudo stack build) &
      pidA=$!

      minutes=0

      while true; do sleep 60; ((minutes++)); echo -e "\033[0;32m$minutes minute(s) elapsed.\033[0m"; done &
      pidB=$!

      wait $pidA

      echo -e "\033[0;32mstack build is finished.\033[0m"

      kill -9 $pidB

      sudo stack test
    fi

 - export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - |
    if [ -z "$STACK" ]; then
      cabal --version
      ghc --version

      
      cabal install --only-dependencies --enable-tests
      cabal configure --enable-tests
      cabal build
      echo -e "\033[0;32mTesting.\033[0m"
      cabal test

      cabal check
      cabal sdist
      cabal install --force-reinstalls dist/*-*.tar.gz
    fi

