sudo: required

env:
 - CABALVER=1.16 GHCVER=7.6.1
 - CABALVER=1.16 GHCVER=7.6.2
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.1
 - CABALVER=1.18 GHCVER=7.8.2
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head
 - STACK=STACK

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head
  - env: CABALVER=1.22 GHCVER=7.10.2

install:
 - sudo apt-get update
 - if [ -n "$STACK" ]; then sudo apt-get install libgmp-dev; fi
 - if [ -z "$STACK" ]; then .travis/ins-cabal.sh; else .travis/ins-stack.sh; fi

script:
 - if [ -n "$STACK" ]; then .travis/stack-build.sh; fi
 - if [ -n "$STACK" ]; then sudo stack test; fi

 - export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - if [ -z "$STACK" ]; then .travis/scr-cabal.sh; fi

