sudo: required

env:
 - CABALVER=1.18 GHCVER=7.8.1
 - CABALVER=1.18 GHCVER=7.8.2
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head
 - STACK=STACK

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head

install:
 - sudo apt-get update
 - if [ -n "$STACK" ]; then sudo apt-get install libgmp-dev; fi
 - |
    set -e
    if [ -z "$STACK" ]; then
      sudo add-apt-repository -y ppa:hvr/ghc
      sudo apt-get update
      time sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
      export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

      echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
      cabal update

    else
      wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
      echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main'|sudo tee /etc/apt/sources.list.d/fpco.list
      sudo apt-get update
      sudo apt-get install stack -y
    fi

script:
 - |
    set -e
    if [ -n "$STACK" ]; then
      echo -e "\033[0;32mstack setup.\033[0m"
      sudo stack setup -v

      echo -e "\033[0;32mstack build.\033[0m"
      sudo stack build -v

      echo -e "\033[0;32mstack test.\033[0m"
      sudo stack test
    fi

 - |
    set -e
    if [ -z "$STACK" ]; then
      cabal --version
      ghc --version
      cabal install happy

      echo -e "\033[0;32mcabal install only deps.\033[0m"
      cabal install --only-dependencies --enable-tests

      echo -e "\033[0;32mcabal config with tests.\033[0m"
      cabal configure --enable-tests

      echo -e "\033[0;32mcabal build.\033[0m"
      cabal build

      echo -e "\033[0;32mcabal test.\033[0m"
      cabal test

      echo -e "\033[0;32mcabal check.\033[0m"
      cabal check

      echo -e "\033[0;32mcabal sdist.\033[0m"
      cabal sdist

      echo -e "\033[0;32mcabal install tarball.\033[0m"
      cabal install --force-reinstalls dist/*-*.tar.gz
    fi

